### ISSUE TITLE
Force re-generation of docs (due to nameclash with removed project)

### ISSUE THREAD

**Issue by bohlender** [adamdruppe/dpldocs#4]
Hey @adamdruppe ,

first of all, this is a very handy project for serving the documentation of all the DUB packages :+1: 

So far it works pretty well - the following issue seems to have gone unnoticed though: When a package's documentation is generated but at some point the package's name changes and another package takes its old name, the cached old documentation is rendered instead of regenerating the one of the new package.

I have this particular issue is with https://capstone-d.dpldocs.info . [capstone-d](https://github.com/bohlender/capstone-d) is a project of mine that provides bindings for a C library. However, I did not try generating it's documentation via https://capstone-d.dpldocs.info until recently (as it was too early to do so). In the meantime someone else created https://github.com/theoldmoon0602/capstone-d and used your service for serving its documentation. I've resolved the name issue with the other package (which is now [d-capstone](https://github.com/theoldmoon0602/d-capstone)) but when I visit [the docs](https://capstone-d.dpldocs.info) I still get to see that project's documentation instead of mine. Is there some way to enforce regeneration of the docs?

Note that in my case this only affects the master branch, e.g. docs for the tag [v0.0.2](https://capstone-d.dpldocs.info/v0.0.2/) had not been generated yet and thus work as expected.

**Comment by adamdruppe** [comment]
I haven't documented this yet since I might change the protocol, but right now if you do

```
curl -d clear http://WHATEVER-PROJECT.dpldocs.info/master/reset-cache
```

You can have it delete its cache and get it rebuilt on next visit to the site. I just did that for capstone-d so it is updated now.

**Comment by bohlender** [comment]
Thanks for the quick reply. I was expecting some undocumented reset-API to exist. This solves my issue.

Keep it up!
