### ISSUE TITLE
std.typecons docs

### ISSUE THREAD

**Issue by John-Colvin** [adamdruppe/dpldocs#5]
At http://dpldocs.info/experimental-docs/std.typecons.html I see 
![image](https://user-images.githubusercontent.com/1867189/52857753-f5da9180-311f-11e9-864c-ddb51540cf2a.png)

and `isTuple` appears to be missing

**Comment by adamdruppe** [comment]
oh interesting, the booktable thing is probably just a minor formatting thing,
but the isTuple I'm guessing is my parser not recognizing the enum = __traits
syntax there. I'll see about fixing it this weekend.

**Comment by adamdruppe** [comment]
fixed it. My parser recognized enum x(T), but it didn't attach the
documentation comment to it!

And the booktable was missing a space, just made it accept that style
too.
