### ISSUE TITLE
OpenSSL broken

### ISSUE THREAD

**Issue by 89z** [adamdruppe/dpldocs#9]
http://openssl.dpldocs.info

~~~
object.Exception@dl.d(544): adrdox failed :(
----------------
??:? void dl.app(arsd.cgi.Cgi) [0x54abc4]
??:? void arsd.cgi.doThreadScgiConnection!(arsd.cgi.Cgi, dl.app(arsd.cgi.Cgi), 5000000L).doThreadScgiConnection(std.socket.Socket) [0x5dae06]
??:? void arsd.cgi.ConnectionThread.run() [0x5d1040]
??:? void core.thread.context.Callable.opCall() [0x605514]
??:? thread_entryPoint [0x604ff7]
??:? [0x7fbee324a6da]
??:? clone [0x7fbee25b1a3e]
~~~

**Comment by adamdruppe** [comment]
On Fri, Mar 19, 2021 at 07:10:59PM -0700, Steven Penny wrote:
> http://openssl.dpldocs.info

I'm trying to rebuild it now, but this looks like it hits the downside
of my "document undocumented" flag... some C bindings just have so many
undocumented items that it explodes the build time...

I need to think of a good solution to that.

**Comment by adamdruppe** [comment]
I turned off the time limit to see how long it took.... 1 hour, 10
minutes.

Well the page works now... but most of it is lacking D documentation
anyway, so it is really just a list of members.

But I have a serious problem to address with this slowness.

**Comment by 89z** [comment]
Thank you for the efforts
